== Introduction

=== Why MicroProfile?

Microservices and microservice architecture walked the path from a silver-bullet-promising buzzword to a largely adopted concept with growing popularity even among big enterprises.
There are multiple success stories about companies that broke their monolith into pieces or started directly with microservices.
Quite a lot of these pieces are developed in Java, so the web application platform vendors quickly jumped on the train.
They all provided their own opinionated approach for the devs to write, deploy and monitor their apps.

The vendors from the Java EE space got on the microservices highway as well.
They were also trying to innovate and come with their own implementation of the different microservice patterns, running on top of the application servers they provide.
But this was definitely not the EE style, which is all about openness and standardization.
However, when it comes to such a hot topic with that traction, the "standards" path is not always the best one.
On one hand, something has to be mature enough to become a standard, which will be followed and supported years ahead.
On the other, the market and the industry doesn't give us that time, and as much as the Java EE vendors care about the standards, they are commercial companies with demanding customers and constant urge to find new ones.

So why not taking a bunch of "de-facto" standards, like the microservices patterns, and quickly turn them into EE specifications?
And probably ship them in a few months with a special release of the umbrella spec?
Because we've already been there and we've made that mistake with EJB CMP: (once) cool looking technology being standardized prematurely.
The difference with the de-facto standards is that they can be easily changed by their de-facto replacement.
Or removed altogether.
While this is not the case with Java EE specification, where the pruning process is much more rigorous.

So what is https://microprofile.io/[MicroProfile]?
It is an initiative which attempts to take the best of both worlds: bring together experts from all the interested parties, make them agree in the open on how should a certain microservice pattern be implemented and put that in an open specification with an open TCK.
Where do these experts come from?
Well, from the Java EE vendors, from other companies, from organizations (like Java User Groups) and even some individuals joined the team to bring their knowledge and energy.

Everything started June 2016.
Then four vendors (RedHat, IBM, Tomitribe and Payara) and an organization (London Java Community) announced version 1 of MicroProfile.
Its first target was not to immediately implement microservice patterns: it did not include any.
It rather aimed at simplicity and at speed.
Both speed to market as well as speed to start.
It defined a minimal MicroProfile runtime, which should be built of three Java EE standards: CDI, JAX-RS and JSON-P.
Having that implemented and working together, makes any server compliant with version 1.

At the end, why MicroProfile?

First of all, because it is open.
The https://github.com/eclipse/microprofile-evolution-process[process to propose] a new specification and the discussions after that are open.
Specifications mailing lists, expert group meetings, issue trackers and TCKs are open.

There's also no single vendor behind it.
So you can be sure that no single company will steer the future and take all the important decisions.
And of course this means that there is no vendor lock in if you decide to choose the MicroProfile approach for your microservice solution.

Does it mean that MicroProfile means that Java EE will no longer be developed?
Not at all!
MicroProfile can be regarded as the incubator project for Java EE.
Or as a playground to experiment with different technologies and see whether they fit and whether they will stand the time to be standardized.
And if they do, why not propose a JSR?

This is exactly what all these vendor had been doing before, but behind closed doors.
Now it is all in the open and we are all invited to take part!

=== Magazine Manager

To showcase the MicroProfile we'll develop together a sample app.
Let's suppose that it is used by an owner of a magazine to manage the various parts of their business.
It consists of four microservices, each of which can be scaled and upgraded separately.

The responsibility of the _Authors_ microservice is to keep track of the authors that are writing for the magazine.
An author has the following properties:

[source,java]
----
public class Author {
    private Long id;
    private String firstName;
    private String lastName;
    private String email;
    private boolean isRegular;
    private int salary;
}
----

In the initial version the microservice should support the following operations:

* Retrieving all the authors
* Finding author by its names
* Finding author by its ID
* Adding an author

The _Content_ microservice takes care of the articles submitted by the authors as well as the comments on those articles.
There are two domain objects in it:

[source,java]
----
public class Article {
    private Long id;
    private String title;
    private String content;
    private String author;
    private List<Comment> comments = new ArrayList<>();
}

public class Comment {
    private Long id;
    private String author;
    private String content;
}
----

Its initial functionality covers things like:

* Retrieving all the articles along with their comments
* Finding an article by its ID
* Retrieving all the articles for an author
* Creating an articles
* Adding a comment to an existing article

We'll go into more details in the Persistence chapter why in `Article` we don't refer directly to the `Author` entity from the _Authors_ microservice.
For now let's assume that we want to explore the http://microservices.io/patterns/data/database-per-service.html[Database per service] pattern.

The third microservice in our list is the _Advertisers_.
As its name implies it contains operations around the magazine's advertisers:

[source,java]
----
public class Advertiser {
    private Long id;
    private String name;
    private String website;
    private String contactEmail;
    private SponsorPackage sponsorPackage;
}

public enum SponsorPackage {

    GOLD(1000), SILVER(500), BRONZE(100);

    private int price;

    SponsorPackage(int price) {
        this.price = price;
    }

    public int getPrice() {
        return price;
    }
}
----

The common functionality that we'll provide with this microservice are these:

* Get all the advertisers
* Find advertiser by name
* Find all the advertisers with a certain sponsor package
* Add an advertiser

Last but not least comes the _Subscriber_ microservice.
Its domain model is as simple as that:

[source, java]
----
public class Subscriber {
    private Long id;
    private String firstName;
    private String lastName;
    private String email;
    private String address;
    private LocalDate subscribedUntil;
}
----

And the operations that we are going to implement are:

* Get the list of all subscribers
* Find subscriber by ID
* Retrieve all the expiring subscriptions
* Add a subscriber

These four microservices at the end will be configured to run on the four runtimes supporting the MicroProfile (one microservice per server).
Basically you will be able to deploy each separate service on every runtime.
However, to keep things simple, we did the following breakdown:

* _Authors_ running on Apache TomEE
* _Content_ running on IBM Liberty Profile
* _Advertisers_ running on WildFly Swarm
* _Subscribers_ running on Payara Micro

In order to follow better the next steps in this lab, we would suggest that you pick the same setup.

=== Initial project

We've sketched for you an initial maven project containing the four microservices as Maven subprojects.
It is located under the `/sources` directory of this lab.
Use your favorite IDE to import that project.
Make sure that it is imported as Maven project for the IDEs that it is not the default structure.

You'll notice that besides the four microservices there is a simple pom project that groups the three specs:

[source, xml]
----
<properties>
    <cdi-version>1.2</cdi-version>
    <jaxrs-version>2.0.1</jaxrs-version>
    <jsonp-version>1.0</jsonp-version>
</properties>

<dependencies>
    <dependency>
        <groupId>javax.enterprise</groupId>
        <artifactId>cdi-api</artifactId>
        <version>${cdi-version}</version>
    </dependency>
    <dependency>
        <groupId>javax.ws.rs</groupId>
        <artifactId>javax.ws.rs-api</artifactId>
        <version>${jaxrs-version}</version>
    </dependency>
    <dependency>
        <groupId>javax.json</groupId>
        <artifactId>javax.json-api</artifactId>
        <version>${jsonp-version}</version>
    </dependency>
</dependencies>
----

By depending on that project instead of `javaee-api`, we will make sure that the microservices we develop will not leak a non-MicroProfile technology like EJB.

The we simply depend on the project by adding the following dependency in the four microservices:

[source, xml]
----
<dependency>
    <groupId>bg.jug</groupId>
    <artifactId>microprofile-dependencies</artifactId>
    <version>${project.version}</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----

Thus they can use the three MicroProfile specs.
The only thing you need to do is to run in the `/sources` directory:

----
mvn clean install
----

After that, you can go to the target directory of each microservice and you'll notice one little war each.
This is the standard format to deliver web applications in Java EE.
So far.

=== How this lab works

In the next few chapters we'll guide you through the process of building a CDI, JAX-RS, JSON-P application, packing it in fat jar instead of war and dealing with persistence.
In each chapter we'll show you the different implementation aspects of two of the microservices (_Author_ and _Content_), while the other two we'll leave to you (with some hints from our side).

You've may also noticed the `solution` directory in the root of this repository.
You can always consult it if the hints are not helpful enough and you don't have whom to ask.
Besides the solution for the current version of the lab, it contains other features that will probably enter in future extensions that we plan to provide.
