== What about persistence?

You may have noticed that the persistence topic is not covered by the first version of MicroProfile.
The reason for that is that it's quite broad.
The default persistence technology for Java EE is JPA, but in a real microservice application you may have lots of different approaches, including NoSQL and JDBC.

That is why, to keep things simple, we are going to store the data of our microservice in the simplest possible store - an in-memory HashMap.

=== The data access objects

Let's add a HashMap field to our `AuthorsDAO` class.
To keep track of the newly created entries IDs, we'll also have an `AtomicLong` field to store the latest ID that we assigned.

[source, java]
----
@ApplicationScoped
public class AuthorDAO {

    private AtomicLong sequence = new AtomicLong(0);
    private Map<Long,Author> authors = new HashMap<>();

    ....
}
----

Now let's add an `addAuthor` method:

[source, java]
----
public void addAuthor(Author author){
    Long authorId = sequence.incrementAndGet();
    author.setId(authorId);
    authors.put(authorId,author);
}
----

Once we have that in place, we'll certainly want our `getAuthors` method to return the content of the map instead of the hard-coded values.
But still, it is good to have bootstrap data to showcase.
So let's move the content of the `getAuthors` method to another one, which we will annotate with the `@PostConstruct` annotation:

[source, java]
----
@PostConstruct
public void addTestData() {
    Author bilboBaggins = new Author("Bilbo", "Baggins", "bilbo@shire.com", true, 1000);
    Author spiderman = new Author("Spider", "Man", "spiderman@comics.com", false, 860);
    Author captainPower = new Author("Captain", "Power", "power@futuresoldiers.com", true, 750);

    addAuthor(bilboBaggins);
    addAuthor(spiderman);
    addAuthor(captainPower);
}
----

This method will be called after the `AuthorsDAO` is constructed and after its dependencies are injected.

Next, let's return the content of the map from the getAuthors method:

[source, java]
----
public List<Author> getAuthors() {
    return new ArrayList<>(authors.values());
}
----

You should do exactly the same for the other microservice DAOs.
For example for `ArticleDAO`:

[source, java]
----
@ApplicationScoped
public class ArticleDAO {

    private AtomicLong sequence = new AtomicLong(0);
    private Map<Long, Article> articles = new ConcurrentHashMap<>();
    private Map<Long, Comment> comments = new ConcurrentHashMap<>();

    public Article addArticle(Article article) {
        Long articleId = sequence.incrementAndGet();
        article.setId(articleId);

        List<Comment> comments = article.getComments();
        if (comments != null) {
            comments.stream()
                    .filter(comment -> comment.getId() == null)
                    .forEach(comment -> comment.setId(sequence.incrementAndGet()));
            comments.forEach(comment -> this.comments.put(comment.getId(), comment));
        }
        articles.put(articleId, article);

        return article;
    }

    public List<Article> getAllArticles() {
        return new ArrayList<>(articles.values());
    }

    @PostConstruct
    public void insertTestData() {
        Article article1 = new Article("Bulgarian JUG’s 2015", "2015 is over and 2016 is a week old now. However, I can’t forget the past year, which happened to be the most active one for the Bulgarian JUG, where I happen to be one of the co-leads. And what a year it was! We had everything: seminar talks with local and foreign speakers, hands on labs, Adopt OpenJDK and Adopt a JSR hackathons, a code retreat and a big international conference. In this blog post I will briefly go through all the events that kept our community busy in 2015.", "Bilbo Baggins");
        Article article2 = new Article("Primitives in Generics, part 3", "In the Bulgarian JUG we had an event dedicated to trying out the OpenJDK Valhalla project’s achievements in the area of using primitive parameters of generics. Our colleague and blogger Mihail Stoynov already wrote about our workshop. I decided, though, to go in a little bit more details and explain the various aspects of the feature.", "Spider Man");
        Article article3 = new Article("Primitives in Generics, part 2", "Whenever the OpenJDK developers want to experiment with a concept they first create a dedicated OpenJDK project for that. This project usually has its own source repository, which is a fork of the OpenJDK sources. It has its page and mailing list and its main purpose is to experiment with ideas for implementing the new concept before creating the Java Enhancement Proposals (JEPs), the Java Specification Requests (JSRs) and committing source code in the real repositories. Features like lambdas, script engine support, method handles and invokedynamic walked this way before entering the official Java release.", "Spider Man");
        Article article4 = new Article("Primitives in Generics, part 1", "Java generics is one of its most widely commented topics. While the discussion whether they should be reified, i.e. the generic parameter information is not erased by javac, is arguably the hottest topic for years now, the lack of support for primitives as parameter types is something that at least causes some confusion. It leads to applying unnecessary boxing when for example you want to put an int into a List (read on to find out about the performance penalty). It also leads to adding “companion” classes in most of the generic APIs, like IntStream and LongStream for example.", "Spider Man");
        Article article5 = new Article("JavaOne, day 4", "The last day at JavaOne started as usual with the community keynote. I didn’t go to it, because I wanted to have a rest after the Aerosmith and Macklemore & Ryan Lewis concert last night and also wanted to catch up with my blogs. However, the people that I follow on twitter were kind enough to update me with the most interesting bits of the session. Additionally, there’s already a blog from Ben Evans about it.", "Captain Power");
        Article article6 = new Article("JavaOne days two and three", "In March this year I had great time at the JavaLand conference. Along with other great people, I met there the freelancer and blog author Roberto Cortez. He told me that he is going to send a few session proposals to JavaOne and asked me whether I wanted to join him for the Java EE Batch talk. I hadn’t heard much about that topic at that time, but I agreed. Then the proposal got accepted and here I am at JavaOne now. What do you know", "Captain Power");

        addArticle(article1);
        addArticle(article2);
        addArticle(article3);
        addArticle(article4);
        addArticle(article5);
        addArticle(article6);
    }
}
----

=== The resources

We have our add methods in place.
So let's expose it via the RESTful webservices.
In order to do that, we'll need a method annotated with `@POST`.

[source, java]
----
@POST
public void addAuthor(String authorJson) {
}
----

We specified that we'll receive the author data as JSON in the POST request body.
So we need a way to convert it to an `Author` object.
Let's add a static factory method in the `Author` class:

[source, java]
----
public static Author fromJson(String json){
    JsonReader reader = Json.createReader(new StringReader(json));
    JsonObject authorObject = reader.readObject();
    reader.close();

    Author author = new Author();
    if (authorObject.containsKey("id")) {
        author.id = authorObject.getJsonNumber("id").longValue();
    }
    author.setFirstName(authorObject.getString("firstName"));
    author.setLastName(authorObject.getString("lastName"));
    author.setEmail(authorObject.getString("email"));
    author.setRegular(authorObject.getBoolean("regular"));
    author.setSalary(authorObject.getInt("salary"));

    return author;
}
----

And now let's call that from our resource method:

[source, java]
----
@POST
public void addAuthor(String authorJson) {
    authorsDAO.addAuthor(Author.fromJson(authorJson));
}
----

Now you can again build and start the author resource:

----
mvn clean install
java -jar target/ROOT-exec.jar
----

Then you can try to add a new author for example with cUrl:

----
curl -H "Content-Type: application/json" -X POST --data '{"firstName": "Mickey", "lastName": "Mouse", "email": "mickey@mouse.org", "salary": 1200, "regular": true}' http://localhost:8080/authors
----

It should be available if you look at `http://localhost:8080/authors`
